<?php
echo $this->getCustomerName();
?>


<form class="form" action="<?php echo $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <fieldset class="fieldset create info">
        <legend class="legend"><span><?php echo __('Personal Information') ?></span></legend>
        <br>
        <div class="field required">
            <label for="first_name" class="label"><span><?php echo __('First Name') ?></span></label>
            <div class="control">
                <input type="text" name="first_name" id="first_name" >
            </div>
        </div>
        <div class="field required">
            <label for="email_address" class="label"><span><?php echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email_address" >
            </div>
        </div>

        <div class="field required">
            <label for="password" class="label"><span><?php echo __('password') ?></span></label>
            <div class="control">
                <input type="password" name="password" id="password" >
            </div>
        </div>


        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?php echo __('Create an Account') ?>">
                    <span><?php echo __('Create an Account') ?></span></button>
            </div>
        </div>
    </fieldset>
</form>

